version: "3"

services:
    server:
        build: ./server
        ports:
            - 4000:4000
        volumes:
            - ./server:/server
        environment:
            - PORT=4000
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASS=postgres
            - POSTGRES_DB=trackingcourse
            - SECRET_KEY=venv9023jfi23kfm2309fh
        depends_on:
            - postgres
        restart: always

    client:
        build: ./client
        ports:
            - 3000:3000
        depends_on:
            - server
        restart: always

    postgres:
        image: postgres
        volumes:
            - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=trackingcourse
        restart: always
